version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: meari_user
      POSTGRES_PASSWORD: meari_password
      POSTGRES_DB: meari_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: